# Generated by Django 4.2.1 on 2023-06-28 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rollno", models.IntegerField()),
                ("name", models.CharField(max_length=30)),
                ("dob", models.DateField()),
                ("marks", models.IntegerField()),
                ("email", models.EmailField(max_length=30)),
                ("phonenumber", models.BigIntegerField()),
                ("address", models.TextField()),
            ],
        ),
    ]
